# Generated by Django 5.1.5 on 2025-01-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('barcode', models.CharField(max_length=255)),
                ('qr_code', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.FloatField()),
                ('rating', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('tags', models.JSONField()),
                ('brand', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('warranty_information', models.CharField(max_length=255)),
                ('shipping_information', models.CharField(max_length=255)),
                ('availability_status', models.CharField(max_length=100)),
                ('return_policy', models.CharField(max_length=255)),
                ('minimum_order_quantity', models.PositiveIntegerField()),
                ('images', models.JSONField()),
                ('thumbnail', models.URLField()),
                ('dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.dimension')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_meta', to='api.metainfo')),
                ('reviews', models.ManyToManyField(related_name='products', to='api.review')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
