# Generated by Django 5.1.5 on 2025-01-25 09:47

from django.db import migrations


def connect_existing_table(apps, schema_editor):
    # The following line prevents Django from attempting to create the table
    # It's like telling Django the table already exists
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(connect_existing_table),
    ]
